server:
  port: 1314
  servlet:
    context-path: /api
# MyBatis Config properties
mybatis:
  type-aliases-package: com.ants.orchid.pojo.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: orchid
  datasource:
    druid:
      url: jdbc:mysql://119.45.7.127:3309/orchid?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
      username: root
      password: 456123
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: none
    timeout: 6000000
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
    cache: false
    encoding: utf-8
#  mail:
#    host: *
#    username: *
#    password: *
#    protocol: smtp
#    default-encoding: UTF-8
#    port: 25
swagger2:
  enable: false